yufu:
  version: 1.1.10
server:
  port: 5001
  compression:
    enabled: true
spring:
  jackson:
    time-zone: GMT+8
  application:
    name: yepshop-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${mysql_url:jdbc:mysql://127.0.0.1:3306/yepshop-dev?characterEncoding=UTF-8&useSSL=false}
    username: ${mysql_username:root}
    password: ${mysql_password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
wechat:
  appid: ${wechat_appid:wx8e7de310601bf8d4}
  secret: ${wechat_secret:475e822dbb4a49969240bcd7c1092522}
  token: ${wechat_token:}
  aesKey: ${wechat_aesKey:}
  pay:
    privateKey: ${wechat_pay_privateKey}
    mchId: ${wechat_pay_mchId}
    mchSerialNo: ${wechat_pay_mchSerialNo}
    notifyUrl: ${notify_url}
aliyun:
  bucket: ${aliyun_bucket}
  ak: ${aliyun_ak}
  sk: ${aliyun_sk}
  region: ${aliyun_region:cn-hangzhou}
  arn: ${aliyun_arn}
  host: ${aliyun_host}