yufu:
  version: 1.2.9
server:
  port: 5001
  compression:
    enabled: true
spring:
  jackson:
    time-zone: GMT+8
  application:
    name: yepshop-service
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${mysql_url:jdbc:mysql://127.0.0.1:3306/yepshop-dev?characterEncoding=UTF-8&useSSL=false}
    username: ${mysql_username:root}
    password: ${mysql_password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
yepxiao:
  filterAuditState: ${filter_audit_state:SUCCESS,PENDING}
wechat:
  appid: ${wechat_appid:}
  secret: ${wechat_secret:}
  token: ${wechat_token:}
  aesKey: ${wechat_aesKey:}
  privateKeyPath: ${wechat_pay_privateKeyPath}
  mchId: ${wechat_pay_mchId}
  mchSerialNo: ${wechat_pay_mchSerialNo}
  notifyUrl: ${notify_url}
  apiV3Key: ${apiV3Key}
aliyun:
  bucket: ${aliyun_bucket}
  ak: ${aliyun_ak}
  sk: ${aliyun_sk}
  region: ${aliyun_region:cn-hangzhou}
  arn: ${aliyun_arn}
  host: ${aliyun_host}